### ISSUE TITLE
[FEATURE REQUEST] make PHP 8 compatible

### ISSUE THREAD

**Issue by dstrop** [subjective-php/psr-cache-helper#16]
i would like to continue using this project in PHP 8

however due to composer requirement for php "^7.0" i am unable to

could you allow php 8 in composer and test against it

**Comment by arron0** [comment]
@chadicus it would be very nice to solve this request :-)
Thank you a lot :-)

**Comment by chadicus** [comment]
PHP 8 is now supported in v2.0.0.
